services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always