name: Build and Run Docker Container

on:
  push:
    branches: [ "backend-flask" ]

jobs:
  Docker-Build-Run:
    runs-on: [self-hosted, Linux]  # pastikan sesuai label runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run and Build Docker container
        run: |
          docker compose up -d --build
      
      - name: Check log container frontend
        run: |
          docker logs frontend
      
      - name: Check log container backend
        run: |
          docker logs backend
